### ISSUE TITLE
Upgrade to Faster-Whisper 1.0.1

### ISSUE THREAD

**Issue by mentesdeltiempo** [jhj0517/Whisper-WebUI#103] opened 2024-03-03 19:39 UTC
It would be great if they updated the integration with Faster-Whisper 1.0.1

**Comment by jhj0517** [comment] 2024-03-06 09:59
It would be better to use the latest version. 
The problem is, if users are using CUDA versions below 12, then it causes errors like #102.
But the migration has to be done, because the latest version would definitely be better.
I made #106 for this, and it should definitely be merged soon.

**Comment by jhj0517** [comment] 2024-03-07 05:43
merged #106 and closing this

**Closed by jhj0517** 2024-03-07 05:43 UTC
Labels: enhancement
