### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Another5405** [jhj0517/Whisper-WebUI#236] opened 2024-08-16 13:46 UTC
**Which OS are you using?**
Window11

My copy was works in few month ago, but now process with bug and I don know why.

Error transcribing file on line HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "C:\App\Whisper-WebUI-master\venv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\App\Whisper-WebUI-master\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\App\Whisper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\App\Whisper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1397, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\App\Whisper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1371, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_youtube) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [textbox, file]
Received outputs:
    [None]

**Comment by jhj0517** [comment] 2024-08-17 10:23
Hi @Another5405. 
It seems that there was an problem with the YouTube API server,  I can't reproduce the error now.

Are you still experiencing the same error?

If you're using the older version of this web ui,
I would recommend updating to the latest version, as I've recently updated pytube to [pytubefix](https://github.com/JuanBindez/pytubefix).

**Comment by consecutiotemporum** [comment] 2024-08-31 13:34
So am I.
I installed Whisper WebUI through Pinokio. Already updated.

**Comment by jhj0517** [comment] 2024-08-31 14:22
This bug occurs whenever youtube updates something in the frontend. 
The bug is handled by `pytubefix`, so you should update `pytubefix` whenever this kind of bug happens.

```
pip install -U pytubefix
```

I just tested it and it works fine with the latest version of `pytubefix`.

**Comment by consecutiotemporum** [comment] 2024-09-01 08:09
The bug is handled by `pytubefix`, so you should update `pytubefix` whenever this kind of bug happens.
> 
> ```
> pip install -U pytubefix
> ```
> 
> I just tested it and it works fine with the latest version of `pytubefix`.

Thanks.
The problem is that Pinokio installation of Whisper-WebUI includes `pytube`, not `pytubefix`.

**Comment by consecutiotemporum** [comment] 2024-09-01 08:25
> The bug is handled by `pytubefix`, so you should update `pytubefix` whenever this kind of bug happens.
> 
> > ```
> > pip install -U pytubefix
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I just tested it and it works fine with the latest version of `pytubefix`.
> 
> Thanks. The problem is that Pinokio installation of Whisper-WebUI includes `pytube`, not `pytubefix`.

Ok. Solved this way:

Changed the `requirements.txt` replacing `pytube` with `pytubefix`.

![Screenshot 2024-09-01 102323](https://github.com/user-attachments/assets/e68be367-f58e-4e62-a9f6-ff3db02db200)

Then I changed the `youtube_manager.py` file replacing the call from `pytube` with `pytubefi`x.

![Screenshot 2024-09-01 102148](https://github.com/user-attachments/assets/152b7f9b-71fe-4bc1-b6dd-d55380ee6d79)

**Comment by jhj0517** [comment] 2024-09-01 10:05
I've never heard of Pinokio before, but I just raised the issue to update the webui - https://github.com/cocktailpeanut/whisper-webui.pinokio/issues/5

**Comment by jhj0517** [comment] 2024-10-15 06:19
This is because of an older version of the web ui, it should now work fine if you reinstall the app in pinokio.

Closing this thread, please feel free to reopen it if you encounter the same bug!

**Closed by jhj0517** 2024-10-15 06:19 UTC
Labels: bug
