### ISSUE TITLE
Can't launch the webui.

### ISSUE THREAD

**Issue by QuantumQuokka2** [jhj0517/Whisper-WebUI#314] opened 2024-10-03 18:51 UTC
**Which OS are you using?** Windows 11
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]

This is what I get after when I run start-web-ui.bat

Traceback (most recent call last):
  File "C:\Users\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\app.py", line 10, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "C:\Users\f\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\modules\whisper\whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "C:\Users\yf\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 16, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "C:\Users\\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\modules\whisper\whisper_base.py", line 13, in <module>
    from modules.uvr.music_separator import MusicSeparator
  File "C:\Users\f\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\modules\uvr\music_separator.py", line 11, in <module>
    from uvr.models import MDX, Demucs, VrNetwork, MDXC
ModuleNotFoundError: No module named 'uvr'
"launching the app"

I've already ran Install.bat and all of the requirements got installed successfully.

**Comment by QuantumQuokka2** [comment] 2024-10-03 18:53
I've checked and uvr is installed. 

Tried both `pip install uvr` and `python -m pip install uvr`

**Comment by QuantumQuokka2** [comment] 2024-10-03 18:55
Also tried the docker and it failed and gave this (failed once I tried to process an audio file.


2024-10-03 20:16:59 app-1  | Use "faster-whisper" implementation
2024-10-03 20:16:59 app-1  | Device "cuda" is detected
2024-10-03 20:16:59 app-1  | Running on local URL:  http://0.0.0.0:7860
2024-10-03 20:17:00 app-1  | 
2024-10-03 20:17:00 app-1  | To create a public link, set share=True in launch().
2024-10-03 20:17:12 app-1  | Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
2036-01-01 00:00:00 
2001-01-01 00:00:00 
                    xited with code 139

**Comment by jhj0517** [comment] 2024-10-04 06:05
Hi @QuantumQuokka2 .

> Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8

Same with #271, You can try to [manually install the dll files](https://github.com/Purfview/whisper-standalone-win/releases/tag/libs) in the system 32 directory. 

Since this happens to so many users, I've been trying to reproduce it, but I keep failing.

Can you do
```
nvcc -V
```

in the terminal and show me what it prints out?

**Comment by jhj0517** [comment] 2024-10-04 12:37
> Could not load library libcudnn_ops_infer.so.8

@QuantumQuokka2 
This has been fixed in https://github.com/jhj0517/Whisper-WebUI/pull/318, and I'm closing this because it's duplicated with #271. 

If you still encounter the bug with the new builds, please let me know.

**Closed by jhj0517** 2024-10-04 12:37 UTC
Labels: bug
